apiVersion: v1
kind: Service
metadata:
  name: ambassador-backend-service
  labels:
    app: backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend
  type: LoadBalancer
