apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: db
      labels:
        app: mysql
    spec:
      containers:
        - name: db
          image: juandperdomoq/ambassador-mysql:latest
          ports:
            - name: mysql-port
              containerPort: 33066
          env:
            - name: MYSQL_DATABASE
              value: "ambassador"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          volumeMounts: 
            - mountPath: /var/lib/mysql
              name: mysql-data
      volumes:
        - name: mysql-data
          emptyDir: {}