apiVersion: v1
kind: Pod
metadata:
  name: ambassador-mysql-pod
  labels:
    app: backend
spec:
  containers:
    - name: db
      image: juandperdomoq/ambassador-mysql:latest
      ports:
        - containerPort: 33066
      env:
        - name: MYSQL_DATABASE
          value: 'ambassador'
        - name: MYSQL_ROOT_PASSWORD
          value: root
      volumeMounts: 
        - mountPath: /var/lib/mysql
          name: mysql-data
  volumes:
    - name: mysql-data
      emptyDir: {}